### ISSUE TITLE
Updating for compatibility with the latest Phasmophobia version

### ISSUE THREAD

**Issue by Astonish42** [alextusinean/tusiphobia#4]
If the game is updated, how should I update it?

**Comment by alextusinean** [comment]
Last Phasmophobia version was released a month ago, what do you want to update? Anyways, the procedure would be regenerating the tusiphobia/appdata folder

**Comment by ctOS-Terminal** [comment]
> the procedure would be regenerating the appdata folder using Il2CppInspector then just updating the sdk.h and sdk.cpp files.

I have tried to figure out how but i have no idea what im doing so could you do an explenation on how to?
