### ISSUE TITLE
Game Freezes on MP if options enabled

### ISSUE THREAD

**Issue by EzequielDM** [alextusinean/tusiphobia#9]
The game will freeze at _Loading 90%_ if you have any options enabled when loading in a game on Multiplayer.
Couldn't reproduce in singleplayer.
Turning all options off makes it work normally and enabling them in-game work fine.

**Comment by alextusinean** [comment]
I never ran into this kind of behaviour. Are you sure this aren't performance issues?

**Comment by EzequielDM** [comment]
100% sure.
30 reruns to be sure.
It only happens when I am host, the only time it did not crash was when I had dead body esp option off, but it crashed the next game with it off too so I'm not sure if that makes any difference.
Tried debugging the game to check what is causing it but the game does not actually crash, it enters a frozen state and I can't pinpoint what part of the code is doing it. I'll try to add breakpoints to some parts of the code to try and check what breakpoints are called before it freezes.

**Comment by alextusinean** [comment]
Are you using the Steam version? Do you have any other modifications?

**Comment by EzequielDM** [comment]
Can't reproduce the issue anymore, all I did was recompile the source. No other modifications. Same checksum as steam.
`29302CC844E82E3F106B366DBF6CD013AA3D8754ACAAA8942A234B8C716E39D9 SHA256 - v0.8.1.7`
I don't play with cheats on Steam, I have a separate folder where I use a local server for online and steam emu.

As I can't reproduce the issue anymore I'll consider this closed, yet if I encounter the issue again I will reopen so you get informed.
